//! `Project -> Sequence[] -> Track[] -> ClipInstance[]`, per spec 4.2.
//!
//! Types only in M0: no edit operations are implemented here (see
//! `edit_ops.rs`), but the shape has been checked on paper against every
//! required edit (ripple/roll/slip/slide, nesting, linked A/V groups,
//! sync-locks) so M3 doesn't discover a structural gap.

use crate::keyframe::ParamTrack;
use crate::time::{FrameRate, TimeTick};
use media::{ColorPrimaries, MediaAssetId};
use serde::{Deserialize, Serialize};

macro_rules! id_type {
    ($name:ident) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
        pub struct $name(pub u64);
    };
}

id_type!(SequenceId);
id_type!(TrackId);
id_type!(ClipInstanceId);
id_type!(MarkerId);
id_type!(LinkedGroupId);
id_type!(EffectInstanceId);
id_type!(TransitionId);
id_type!(BinId);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TrackKind {
    Video,
    Audio,
}

/// What a `ClipInstance` actually plays back. `NestedSequence` is spec 4.2's
/// "a sequence used as a clip inside another sequence" — the seam is here
/// from M0 even though multicam (which also nests) is deferred to v1.1.
///
/// No longer `Copy`/`Eq` since `Title` carries an owned `String` and `f64`s.
/// That's a deliberate trade: a title's appearance genuinely is part of what
/// the clip plays, and hiding it behind an id would mean inventing a
/// title-asset table that exists only to keep this enum two words wide.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ClipSource {
    Media(MediaAssetId),
    NestedSequence(SequenceId),
    /// A text title, generated by the renderer rather than decoded from a
    /// file. It carries its whole appearance inline instead of referencing an
    /// asset because there is no file to reference — the clip *is* the source,
    /// which is also why editing the text is an ordinary project mutation and
    /// goes through undo like any other.
    Title(TitleSpec),
}

/// Where a line of title text sits relative to its anchor point.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TextAlign {
    Left,
    Center,
    Right,
}

/// Everything needed to draw a title. Deliberately plain data with no handles
/// into a font cache or GPU state, so it serialises into the project file and
/// compares by value for undo coalescing like the rest of the model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TitleSpec {
    pub text: String,
    /// Family name resolved against installed system fonts at draw time. Not a
    /// path: a project that hardcoded `C:\Windows\Fonts\arial.ttf` would not
    /// open on another machine, whereas an unresolvable *family* can fall back
    /// to a default and still render something.
    pub font_family: String,
    pub size_px: f64,
    /// Rec.709-encoded RGBA in 0..1 — the values a colour picker hands you,
    /// matching how every decoded source arrives. The compositor linearises it
    /// on the way in like any other Rec.709 source, so a title and a clip of
    /// the same colour composite identically.
    pub color: [f64; 4],
    pub align: TextAlign,
    /// Anchor position as a fraction of the frame, (0,0) top-left to (1,1)
    /// bottom-right. `align` decides what the x component anchors (the left
    /// edge, centre, or right edge of the widest line); y is always the
    /// vertical centre of the whole text block, which is what makes a title
    /// stay put when a line is added to it.
    pub position: (f64, f64),
}

impl Default for TitleSpec {
    fn default() -> Self {
        TitleSpec {
            text: "Title".into(),
            font_family: "Arial".into(),
            size_px: 72.0,
            color: [1.0, 1.0, 1.0, 1.0],
            align: TextAlign::Center,
            position: (0.5, 0.5),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SpeedCurve {
    /// e.g. 200% speed = Constant { numerator: 2, denominator: 1 }.
    Constant { numerator: i64, denominator: i64 },
    /// Keyframed rate; resolving timeline-tick -> source-tick under a
    /// non-constant curve is M7 (time remapping) work.
    Keyframed(ParamTrack),
}

impl SpeedCurve {
    /// Converts a timeline-tick delta into the corresponding source-tick
    /// delta. Exact for `Constant`.
    ///
    /// For `Keyframed` this returns the 1x (unmodified) delta: correctly
    /// integrating a keyframed rate curve to get elapsed source time is
    /// time-remapping (M7), and a wrong-but-plausible approximation here
    /// would silently desync audio against video. Returning 1x is at least
    /// a predictable, documented placeholder rather than a guess — every
    /// caller in `timeline` and `render` funnels through this one function,
    /// so M7 has exactly one place to fix.
    pub fn source_delta(&self, timeline_delta: i64) -> i64 {
        match self {
            SpeedCurve::Constant { numerator, denominator } if *denominator != 0 => {
                timeline_delta * numerator / denominator
            }
            _ => timeline_delta,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EffectInstance {
    pub id: EffectInstanceId,
    /// Matches an `EffectDescriptor::type_id` in the render crate's registry.
    /// Stored as a string (not a render-crate enum) so `timeline` never has
    /// to depend on `render`.
    pub effect_type: String,
    pub enabled: bool,
    pub params: std::collections::BTreeMap<String, ParamTrack>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ClipInstance {
    pub id: ClipInstanceId,
    pub source: ClipSource,
    pub source_in: TimeTick,
    pub source_out: TimeTick,
    pub timeline_in: TimeTick,
    pub timeline_out: TimeTick,
    pub speed: SpeedCurve,
    pub effects: Vec<EffectInstance>,
    pub audio_gain_db: ParamTrack,
    pub audio_pan: ParamTrack,
    pub linked_group: Option<LinkedGroupId>,
}

impl ClipInstance {
    pub fn timeline_duration(&self) -> TimeTick {
        TimeTick(self.timeline_out.0 - self.timeline_in.0)
    }
}

/// A track fader at unity — the default, what an old project without the
/// field reads as, and what every caller constructing a `Track` by hand
/// wants. Public because `Track::gain_db` stopped being a bare `0.0` anyone
/// could write inline.
pub fn unity_gain() -> ParamTrack {
    ParamTrack::constant(crate::keyframe::ParamValue::Number(0.0))
}

/// Accepts either a bare number (schema v5 and earlier) or a full
/// `ParamTrack` (v6+). See `Track::gain_db` for why this compat can't live in
/// the migration chain.
fn deserialize_gain_db<'de, D>(deserializer: D) -> Result<ParamTrack, D::Error>
where
    D: serde::Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum GainDb {
        // Ordered with the scalar first: a v6 `ParamTrack` is a map and a v5
        // fader is a number, so the two can't be confused either way round,
        // but trying the cheap shape first keeps the common case cheap.
        Static(f64),
        Automated(ParamTrack),
    }
    Ok(match GainDb::deserialize(deserializer)? {
        GainDb::Static(db) => ParamTrack::constant(crate::keyframe::ParamValue::Number(db)),
        GainDb::Automated(track) => track,
    })
}

/// What a transition does between its two clips.
///
/// Kept as an enum rather than a generic effect because a transition takes
/// **two** inputs, which the single-input-per-clip effect chain can't express
/// at all — see `render::graph`'s `TransitionRender`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TransitionKind {
    /// The outgoing clip mixes directly into the incoming one.
    CrossDissolve,
    /// The outgoing clip dims to black over the first half, the incoming one
    /// brightens out of it over the second. It dims the clip's **colour** at
    /// full alpha rather than fading its alpha, so the track keeps covering
    /// whatever is on the tracks below for the whole transition — fading alpha
    /// instead looked right only on the bottom track and let lower tracks show
    /// through the dip everywhere else.
    DipToBlack,
    /// A hard-edged boundary sweeps left to right, revealing the incoming clip
    /// behind it. Unlike a dissolve, both clips are fully opaque at every
    /// point — the transition is *where* each one is drawn, not how
    /// transparent it is.
    ///
    /// Left-to-right only. Other directions (right-to-left, vertical,
    /// diagonal, barn-door) would each need a direction field on `Transition`,
    /// which is a schema change rather than a rendering one; deliberately not
    /// guessed at here.
    Wipe,
    /// The incoming clip slides in from the right over a stationary outgoing
    /// clip, fully opaque the whole way.
    ///
    /// Purely a position offset — no shader involvement at all, since
    /// `Transform2D::position` already places a clip wherever it needs to be.
    /// Like `Wipe`, one direction only, for the same reason.
    Slide,
}

impl TransitionKind {
    /// Every kind, for UI that offers a choice of transition. Exhaustive by
    /// construction: the `match` in `label` fails to compile if a variant is
    /// added without being handled, and a menu built from this array then
    /// picks it up for free — which is what stops a kind being implemented in
    /// the renderer but left unreachable in the editor.
    pub const ALL: [TransitionKind; 4] = [
        TransitionKind::CrossDissolve,
        TransitionKind::DipToBlack,
        TransitionKind::Wipe,
        TransitionKind::Slide,
    ];

    /// Human-readable name, as it should appear in a menu.
    pub fn label(self) -> &'static str {
        match self {
            TransitionKind::CrossDissolve => "Cross Dissolve",
            TransitionKind::DipToBlack => "Dip to Black",
            TransitionKind::Wipe => "Wipe",
            TransitionKind::Slide => "Slide",
        }
    }
}

/// A transition straddling one cut on one track.
///
/// Anchored to the cut (`at`) and centred on it, which is how an editor thinks
/// about it ("put a 1-second dissolve on this cut") and what keeps it attached
/// to the right edit when neighbouring clips are trimmed.
///
/// The transition region extends `duration / 2` either side of the cut, so both
/// clips are sampled **past their own trim points** during it — into their
/// handles, exactly like a real NLE. Where a clip has no handle material the
/// decoder holds its nearest frame instead of failing, so a dissolve on
/// footage trimmed to its very last frame degrades to a freeze rather than an
/// error.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Transition {
    pub id: TransitionId,
    pub kind: TransitionKind,
    /// The cut this straddles, in sequence time.
    pub at: TimeTick,
    /// Total length, centred on `at`.
    pub duration: TimeTick,
}

impl Transition {
    /// Half-open sequence-time range this transition affects.
    pub fn region(&self) -> (TimeTick, TimeTick) {
        let half = self.duration.0 / 2;
        (TimeTick(self.at.0 - half), TimeTick(self.at.0 - half + self.duration.0))
    }

    pub fn covers(&self, at: TimeTick) -> bool {
        let (start, end) = self.region();
        self.duration.0 > 0 && start <= at && at < end
    }

    /// How far through the transition `at` is, clamped to 0..=1.
    pub fn progress_at(&self, at: TimeTick) -> f32 {
        if self.duration.0 <= 0 {
            return 1.0;
        }
        let (start, _) = self.region();
        (((at.0 - start.0) as f64) / (self.duration.0 as f64)).clamp(0.0, 1.0) as f32
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Track {
    pub id: TrackId,
    pub kind: TrackKind,
    pub name: String,
    /// Invariant: sorted by `timeline_in`, non-overlapping. Enforced by edit
    /// ops (M3), checked by `invariants::check_no_overlaps` and the
    /// property-based test suite.
    pub clips: Vec<ClipInstance>,
    /// Transitions on this track's cuts. `serde(default)` so projects written
    /// before schema v3 still load — see `project::persist`'s migration chain.
    #[serde(default)]
    pub transitions: Vec<Transition>,
    /// Track fader, in dB, keyframeable. `0.0` is unity, which is why
    /// `serde(default)` is safe here — a project written before faders existed
    /// reads as every track at unity, i.e. exactly how it used to sound.
    ///
    /// **Was a plain `f64` through schema v5.** `deserialize_gain_db` reads
    /// either form, so a v5 project's bare number decodes as a constant track
    /// with no data loss. That compat lives in the deserializer rather than in
    /// `project::persist::migrate` for a structural reason: migration runs
    /// *after* decoding, and decoding a bare CBOR float into a `ParamTrack`
    /// fails before migration ever gets a chance to run. The rule that every
    /// format change needs a real migration is about old files still opening;
    /// for a field whose *type* changed, this is the only place that can be
    /// honoured.
    #[serde(default = "unity_gain", deserialize_with = "deserialize_gain_db")]
    pub gain_db: ParamTrack,
    /// Track pan, -1.0 (hard left) to 1.0 (hard right). `0.0` is centre.
    #[serde(default)]
    pub pan: f64,
    pub locked: bool,
    pub sync_locked: bool,
    pub muted: bool,
    pub solo: bool,
    pub height_px: u32,
}

impl Track {
    /// The transition active at `at`, if any. Transitions are anchored to
    /// distinct cuts, so at most one can cover a given tick in a well-formed
    /// project; the first match wins if that's ever violated.
    pub fn transition_at(&self, at: TimeTick) -> Option<&Transition> {
        self.transitions.iter().find(|t| t.covers(at))
    }

    /// The clip ending exactly at `cut` and the one starting there — the pair a
    /// transition anchored at `cut` bridges. `None` for either side when there
    /// is no clip there, which is how a transition at the head or tail of a
    /// clip becomes a plain fade in/out rather than an error.
    pub fn clips_at_cut(&self, cut: TimeTick) -> (Option<&ClipInstance>, Option<&ClipInstance>) {
        (
            self.clips.iter().find(|c| c.timeline_out == cut),
            self.clips.iter().find(|c| c.timeline_in == cut),
        )
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Marker {
    pub id: MarkerId,
    pub position: TimeTick,
    pub duration: TimeTick,
    pub name: String,
    pub comment: String,
    pub color: [f32; 4],
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SequenceSettings {
    pub frame_rate: FrameRate,
    pub width: u32,
    pub height: u32,
    pub sample_rate: u32,
    pub working_color_primaries: ColorPrimaries,
    pub drop_frame_timecode: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sequence {
    pub id: SequenceId,
    pub name: String,
    pub settings: SequenceSettings,
    pub tracks: Vec<Track>,
    pub markers: Vec<Marker>,
}

impl Sequence {
    /// Derived, not stored: the end of the last clip across all tracks.
    /// Never cache this on the struct — it would need updating on every
    /// edit and could drift; recomputing is O(clips) and cheap.
    pub fn duration(&self) -> TimeTick {
        self.tracks
            .iter()
            .flat_map(|t| t.clips.iter())
            .map(|c| c.timeline_out)
            .max()
            .unwrap_or(TimeTick::ZERO)
    }
}

/// The whole document. Every edit produces a new `Project` value; nothing
/// mutates a `Project` in place. `Arc<Project>` is what actually flows
/// through the app as a cheap-to-clone version snapshot — see
/// `command::UndoStack`.
///
/// M0 note: this uses ordinary `Vec`/`BTreeMap`, so producing a "new version"
/// today means cloning whatever subtree changed, not true structural sharing.
/// If profiling on 500+-clip sequences (the M0 risk list item) shows clone
/// cost is a problem, the fix is swapping in a persistent-vector crate (e.g.
/// `im`) behind these same types — that's a decision to make with real
/// numbers, not now.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Project {
    pub sequences: Vec<Sequence>,
    pub assets: Vec<media::MediaAsset>,
    /// Folders organising the project's assets and sequences, like
    /// Premiere's Project panel bins. Empty means everything sits at the
    /// root.
    ///
    /// `#[serde(default)]` so project files written before bins existed still
    /// load — see `project::persist`'s migration chain.
    #[serde(default)]
    pub bins: Vec<Bin>,
}

/// One thing a bin can hold. Bins carry *references*, so moving an item
/// between bins never touches the item itself — and a `MediaAsset` stays the
/// immutable ingest-time record it's documented to be (spec 4.1), with
/// organisation living in the project where it belongs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BinItem {
    Asset(MediaAssetId),
    Sequence(SequenceId),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Bin {
    pub id: BinId,
    pub name: String,
    /// `None` = a top-level bin (child of the implicit project root).
    pub parent: Option<BinId>,
    pub items: Vec<BinItem>,
}

impl Project {
    /// Which bin holds `item`, or `None` when it sits at the root.
    ///
    /// Membership is stored on the bin rather than the item, so this is a
    /// search. Bin counts are small (tens, not thousands) and this is only
    /// called from UI code that's already walking the tree, so the simple
    /// direction is the right one until profiling says otherwise.
    pub fn bin_of(&self, item: BinItem) -> Option<BinId> {
        self.bins.iter().find(|b| b.items.contains(&item)).map(|b| b.id)
    }

    /// Everything not inside any bin — what the Project panel shows at the
    /// top level. Assets come before sequences, each in project order, so
    /// the panel's default ordering is stable across reloads.
    pub fn root_items(&self) -> Vec<BinItem> {
        let assets = self.assets.iter().map(|a| BinItem::Asset(a.id));
        let sequences = self.sequences.iter().map(|s| BinItem::Sequence(s.id));
        assets
            .chain(sequences)
            .filter(|item| self.bin_of(*item).is_none())
            .collect()
    }

    /// Direct child bins of `parent` (`None` for top level).
    pub fn child_bins(&self, parent: Option<BinId>) -> Vec<&Bin> {
        self.bins.iter().filter(|b| b.parent == parent).collect()
    }

    /// True if `candidate_parent` is `bin` itself or somewhere beneath it —
    /// the check that stops a "move bin into bin" from creating a cycle that
    /// would make the tree walk infinite.
    pub fn is_descendant_of(&self, candidate_parent: BinId, bin: BinId) -> bool {
        if candidate_parent == bin {
            return true;
        }
        let mut current = candidate_parent;
        // Bounded by bin count so a pre-existing cycle can't hang this.
        for _ in 0..=self.bins.len() {
            match self.bins.iter().find(|b| b.id == current).and_then(|b| b.parent) {
                Some(parent) if parent == bin => return true,
                Some(parent) => current = parent,
                None => return false,
            }
        }
        false
    }
}

pub mod invariants {
    use super::Track;

    #[derive(Debug, PartialEq, Eq)]
    pub enum InvariantViolation {
        Overlap { first: usize, second: usize },
        NotSortedByTimelineIn { index: usize },
    }

    /// Real, tested logic (not a stub) — this is the primitive the M3
    /// property-based test suite (spec 4.2 "Gap and collision invariants")
    /// is built on top of.
    pub fn check_no_overlaps(track: &Track) -> Result<(), InvariantViolation> {
        for i in 1..track.clips.len() {
            if track.clips[i].timeline_in < track.clips[i - 1].timeline_in {
                return Err(InvariantViolation::NotSortedByTimelineIn { index: i });
            }
            if track.clips[i].timeline_in < track.clips[i - 1].timeline_out {
                return Err(InvariantViolation::Overlap { first: i - 1, second: i });
            }
        }
        Ok(())
    }

    /// Why a whole project is structurally unusable.
    #[derive(Debug, PartialEq, Eq)]
    pub enum ProjectViolation {
        Overlap { track: super::TrackId },
        /// A clip that ends before it starts, or occupies no time at all.
        EmptyOrInvertedClip { clip: super::ClipInstanceId },
        /// A clip starting before the beginning of the sequence.
        NegativeStart { clip: super::ClipInstanceId },
        /// A clip whose source range runs backwards.
        InvertedSourceRange { clip: super::ClipInstanceId },
        DuplicateClipId(super::ClipInstanceId),
        DuplicateTrackId(super::TrackId),
        DuplicateSequenceId(super::SequenceId),
        /// A sequence whose audio rate can't be used as one.
        InvalidSampleRate { sequence: super::SequenceId, rate: u32 },
        /// A sequence with no frame to render into.
        InvalidFrameSize { sequence: super::SequenceId, width: u32, height: u32 },
    }

    /// Checks a whole project the way `edit_ops::apply` checks its own
    /// result — the same standard, applied to projects that arrive from
    /// disk rather than from an edit.
    ///
    /// Clip storage order is *normalised* first rather than rejected:
    /// `apply` sorts before it checks for exactly this reason (operations
    /// that move a clip in place leave the vec out of order without
    /// anything being wrong), so a differently-ordered vec is not
    /// corruption and must not be treated as any.
    ///
    /// Everything else here is a claim no edit could have produced, and
    /// that later code is entitled to assume: a mixer asked for a clip
    /// ending before it starts, or two clips answering to one id, has no
    /// correct behaviour available to it.
    pub fn check_project(project: &mut super::Project) -> Result<(), ProjectViolation> {
        let mut seen_sequences = std::collections::HashSet::new();
        let mut seen_tracks = std::collections::HashSet::new();
        let mut seen_clips = std::collections::HashSet::new();

        for sequence in &mut project.sequences {
            if !seen_sequences.insert(sequence.id) {
                return Err(ProjectViolation::DuplicateSequenceId(sequence.id));
            }
            // Divided by and used to size buffers all over the audio path,
            // and a frame of no size is not something the renderer can
            // target. Bounds rather than "nonzero": a rate of four billion
            // is as unusable as a rate of zero, just further from the
            // arithmetic that would notice.
            if !(8_000..=768_000).contains(&sequence.settings.sample_rate) {
                return Err(ProjectViolation::InvalidSampleRate {
                    sequence: sequence.id,
                    rate: sequence.settings.sample_rate,
                });
            }
            if sequence.settings.width == 0 || sequence.settings.height == 0 {
                return Err(ProjectViolation::InvalidFrameSize {
                    sequence: sequence.id,
                    width: sequence.settings.width,
                    height: sequence.settings.height,
                });
            }

            for track in &mut sequence.tracks {
                if !seen_tracks.insert(track.id) {
                    return Err(ProjectViolation::DuplicateTrackId(track.id));
                }
                for clip in &track.clips {
                    if !seen_clips.insert(clip.id) {
                        return Err(ProjectViolation::DuplicateClipId(clip.id));
                    }
                    if clip.timeline_in.0 < 0 {
                        return Err(ProjectViolation::NegativeStart { clip: clip.id });
                    }
                    if clip.timeline_out.0 <= clip.timeline_in.0 {
                        return Err(ProjectViolation::EmptyOrInvertedClip { clip: clip.id });
                    }
                    if clip.source_out.0 < clip.source_in.0 {
                        return Err(ProjectViolation::InvertedSourceRange { clip: clip.id });
                    }
                }
                track.clips.sort_by_key(|c| c.timeline_in.0);
                if check_no_overlaps(track).is_err() {
                    return Err(ProjectViolation::Overlap { track: track.id });
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::invariants::*;
    use super::*;

    fn clip(id: u64, tin: i64, tout: i64) -> ClipInstance {
        ClipInstance {
            id: ClipInstanceId(id),
            source: ClipSource::Media(MediaAssetId(0)),
            source_in: TimeTick(0),
            source_out: TimeTick(tout - tin),
            timeline_in: TimeTick(tin),
            timeline_out: TimeTick(tout),
            speed: SpeedCurve::Constant { numerator: 1, denominator: 1 },
            effects: vec![],
            audio_gain_db: ParamTrack::constant(crate::keyframe::ParamValue::Number(0.0)),
            audio_pan: ParamTrack::constant(crate::keyframe::ParamValue::Number(0.0)),
            linked_group: None,
        }
    }

    fn track_with(clips: Vec<ClipInstance>) -> Track {
        Track {
            id: TrackId(0),
            kind: TrackKind::Video,
            name: "V1".into(),
            clips,
            transitions: vec![], gain_db: unity_gain(), pan: 0.0,
            locked: false,
            sync_locked: true,
            muted: false,
            solo: false,
            height_px: 60,
        }
    }

    #[test]
    fn adjacent_non_overlapping_clips_pass() {
        let track = track_with(vec![clip(1, 0, 100), clip(2, 100, 200)]);
        assert_eq!(check_no_overlaps(&track), Ok(()));
    }

    #[test]
    fn overlapping_clips_are_rejected() {
        let track = track_with(vec![clip(1, 0, 100), clip(2, 50, 200)]);
        assert_eq!(
            check_no_overlaps(&track),
            Err(InvariantViolation::Overlap { first: 0, second: 1 })
        );
    }

    #[test]
    fn out_of_order_clips_are_rejected() {
        let track = track_with(vec![clip(1, 100, 200), clip(2, 0, 50)]);
        assert_eq!(
            check_no_overlaps(&track),
            Err(InvariantViolation::NotSortedByTimelineIn { index: 1 })
        );
    }

    // --- bins ---

    fn asset(id: u128) -> media::MediaAsset {
        media::MediaAsset {
            id: MediaAssetId(id),
            original_absolute_path: format!("C:/m/{id}.mp4"),
            content_hash: [0u8; 32],
            container_format: "mp4".into(),
            video: None,
            audio: None,
            duration_ticks: 0,
        }
    }

    fn bin(id: u64, parent: Option<u64>, items: Vec<BinItem>) -> Bin {
        Bin { id: BinId(id), name: format!("Bin {id}"), parent: parent.map(BinId), items }
    }

    fn project_with_bins(bins: Vec<Bin>) -> Project {
        Project {
            sequences: vec![Sequence {
                id: SequenceId(1),
                name: "S".into(),
                settings: SequenceSettings {
                    frame_rate: FrameRate::Fps30,
                    width: 640,
                    height: 360,
                    sample_rate: 48_000,
                    working_color_primaries: ColorPrimaries::Rec709,
                    drop_frame_timecode: false,
                },
                tracks: vec![],
                markers: vec![],
            }],
            assets: vec![asset(1), asset(2)],
            bins,
        }
    }

    #[test]
    fn items_not_in_any_bin_are_reported_at_the_root() {
        // Asset 1 filed away, asset 2 and the sequence still loose.
        let project = project_with_bins(vec![bin(10, None, vec![BinItem::Asset(MediaAssetId(1))])]);

        let root = project.root_items();

        assert!(!root.contains(&BinItem::Asset(MediaAssetId(1))), "filed asset should leave the root");
        assert!(root.contains(&BinItem::Asset(MediaAssetId(2))));
        assert!(
            root.contains(&BinItem::Sequence(SequenceId(1))),
            "sequences live in the Project panel too, so they show at the root"
        );
        assert_eq!(project.bin_of(BinItem::Asset(MediaAssetId(1))), Some(BinId(10)));
        assert_eq!(project.bin_of(BinItem::Asset(MediaAssetId(2))), None);
    }

    #[test]
    fn child_bins_are_listed_per_parent() {
        let project = project_with_bins(vec![
            bin(10, None, vec![]),
            bin(11, Some(10), vec![]),
            bin(12, Some(10), vec![]),
            bin(13, None, vec![]),
        ]);

        let top: Vec<u64> = project.child_bins(None).iter().map(|b| b.id.0).collect();
        assert_eq!(top, vec![10, 13]);
        let under_10: Vec<u64> = project.child_bins(Some(BinId(10))).iter().map(|b| b.id.0).collect();
        assert_eq!(under_10, vec![11, 12]);
    }

    #[test]
    fn descendant_check_blocks_moving_a_bin_into_its_own_subtree() {
        // 10 > 11 > 12
        let project = project_with_bins(vec![
            bin(10, None, vec![]),
            bin(11, Some(10), vec![]),
            bin(12, Some(11), vec![]),
            bin(20, None, vec![]),
        ]);

        // Dropping 10 into 12 would make the tree circular.
        assert!(project.is_descendant_of(BinId(12), BinId(10)), "12 is under 10");
        assert!(project.is_descendant_of(BinId(10), BinId(10)), "a bin is its own descendant");
        assert!(!project.is_descendant_of(BinId(20), BinId(10)), "20 is a sibling, not a descendant");
        assert!(!project.is_descendant_of(BinId(10), BinId(12)), "the check is directional");
    }

    #[test]
    fn descendant_check_terminates_on_an_already_cyclic_tree() {
        // A corrupt/hand-edited file could contain a cycle; the walk must
        // return rather than spin forever, since it runs inside the UI's
        // per-frame tree traversal.
        let project = project_with_bins(vec![bin(10, Some(11), vec![]), bin(11, Some(10), vec![])]);
        assert!(!project.is_descendant_of(BinId(10), BinId(99)));
    }
}

#[cfg(test)]
mod transition_kind_tests {
    use super::TransitionKind;

    #[test]
    fn every_kind_is_listed_in_all_and_has_a_distinct_label() {
        // `ALL` is a hand-written array, so nothing but a test stops it
        // drifting out of sync with the enum after a variant is added. Labels
        // must be distinct too — two menu entries reading the same thing is a
        // UI bug that compiles perfectly well.
        let labels: Vec<&str> = TransitionKind::ALL.iter().map(|k| k.label()).collect();
        let mut unique = labels.clone();
        unique.sort_unstable();
        unique.dedup();
        assert_eq!(unique.len(), labels.len(), "duplicate transition labels: {labels:?}");
        assert!(!labels.iter().any(|l| l.is_empty()), "every kind needs a label");
    }
}
